# Generated by Django 3.1.3 on 2020-12-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201201_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
