# Generated by Django 3.1.3 on 2020-12-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201201_1005'),
        ('order', '0002_auto_20201201_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
