# Generated by Django 3.1.3 on 2021-03-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210309_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(null='True'),
            preserve_default='True',
        ),
    ]
