# Generated by Django 3.1.3 on 2020-12-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201130_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
