# Generated by Django 3.1.3 on 2020-12-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201201_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty',
        ),
    ]
