# Generated by Django 3.1.3 on 2020-12-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201201_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='value',
        ),
    ]
